# Data type

In [2]:
import numpy as np

var = np.array([1,2,3,4]) # array of integer data types
print("Data type : ", var.dtype)

Data type :  int64


In [3]:
var = np.array([1.4,2.5,3.1,4.0]) # array of float data types
print("Data type : ", var.dtype)

Data type :  float64


In [5]:
var = np.array(["A","B","C","d"]) # array of unicode string data types <U1 , <U2 etc
print("Data type : ", var.dtype)

Data type :  <U1


In [6]:
var = np.array([1,2,3,4, "A"]) # array of number and string data types <U11 , <U12 etc
print("Data type : ", var.dtype)

Data type :  <U21


In [8]:
var = np.array([1,2,3,4], dtype = np.int8) # convert to int8
print("Data type : ", var.dtype)

Data type :  int8


In [9]:
var = np.array([1,2,3,4], dtype = "f") # convert to float (if know short hand)
print("Data type : ", var.dtype)

Data type :  float32


In [11]:
var = np.array([1,2,3,4]) # array of integer data types
new = np.float32(var) # convert to float
revert = np.int_(new) # revert
print("Data type : ", var.dtype)
print("Data type : ", new.dtype)
print("Data type : ", revert.dtype)

print(var)
print(new)
print(revert)

Data type :  int64
Data type :  float32
Data type :  int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [12]:
var = np.array([1,2,3,4])
new = var.astype(float)

print(var)
print(new)

[1 2 3 4]
[1. 2. 3. 4.]
