# Iteration

In [1]:
import numpy as np

# using traditional for-in loop

In [5]:
# for 1-D
arr = np.array([1, 2, 3, 4])
print(arr.ndim)
print(arr)
print()
for i in arr:
    print(i)

1
[1 2 3 4]

1
2
3
4


In [6]:
# for 2-D
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.ndim)
print(arr)
print()

for i in arr:
    print(i)
    
print()

for j in arr:
    for k in i:
        print(k)

2
[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

5
6
7
8
5
6
7
8


In [7]:
# for 3-D
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(arr.ndim)
print(arr)
print()

for i in arr:
    print(i)
    
print()

for j in arr:
    for k in i:
        print(k)
        
print()

for j in arr:
    for k in i:
        for l in k:
            print(l)

3
[[[1 2 3 4]
  [5 6 7 8]]]

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


# using for-in and np.nditer()

In [8]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(arr.ndim)
print(arr)
print()

for i in np.nditer(arr):
    print(i)

3
[[[1 2 3 4]
  [5 6 7 8]]]

1
2
3
4
5
6
7
8


In [9]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(arr.ndim)
print(arr)
print()

for i in np.nditer(arr, flags=['buffered'], op_dtypes=["S"]):  # a buffer of String (S) data will generate
    print(i)

3
[[[1 2 3 4]
  [5 6 7 8]]]

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [10]:
# iteration with values as well as their indexes
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]]])
print(arr.ndim)
print(arr)
print()

for i, d in np.ndenumerate(arr):
    print(i, d)

3
[[[1 2 3 4]
  [5 6 7 8]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
