# Join Array

In [1]:
import numpy as np

# using concatenate

In [3]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.concatenate((arr1, arr2))
print(merged_arr)

[ 1  2  3  4 10 20 30 40]


In [5]:
# 2-D
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10, 20], [30, 40]])

merged_arr = np.concatenate((arr1, arr2), axis=1) # 1 -> along row, 0 -> along column
print(arr1)
print()
print(arr2)
print()
print(merged_arr)

[[1 2]
 [3 4]]

[[10 20]
 [30 40]]

[[ 1  2 10 20]
 [ 3  4 30 40]]


In [6]:
# 2-D
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[10, 20], [30, 40]])

merged_arr = np.concatenate((arr1, arr2), axis=0) # 1 -> along row, 0 -> along column
print(arr1)
print()
print(arr2)
print()
print(merged_arr)

[[1 2]
 [3 4]]

[[10 20]
 [30 40]]

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


# using stack

In [7]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.stack((arr1, arr2), axis = 1) # 1 -> along row, 0 -> along column
print(merged_arr)

[[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]]


In [8]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.stack((arr1, arr2), axis = 0) # 1 -> along row, 0 -> along column
print(merged_arr)

[[ 1  2  3  4]
 [10 20 30 40]]


In [9]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.hstack((arr1, arr2)) # h -> along row (horizontally)
print(merged_arr)

[ 1  2  3  4 10 20 30 40]


In [10]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.vstack((arr1, arr2)) # v -> along column (vertically)
print(merged_arr)

[[ 1  2  3  4]
 [10 20 30 40]]


In [11]:
# 1-D
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

merged_arr = np.dstack((arr1, arr2)) # d -> along height (diagonally)
print(merged_arr)

[[[ 1 10]
  [ 2 20]
  [ 3 30]
  [ 4 40]]]


# Split Array

In [13]:
# 1-D
arr = np.array([1, 2, 3, 4])
print(arr)
splt = np.array_split(arr, 2) # in two equal parts
print()
print(splt)
print()
print(splt[0])
print(splt[1])

[1 2 3 4]

[array([1, 2]), array([3, 4])]

[1 2]
[3 4]


In [14]:
# 2-D
arr = np.array([[1, 2], [3, 4]])
print(arr)
splt = np.array_split(arr, 2) # in two equal parts
print()
print(splt)
print()
print(splt[0])
print(splt[1])

[[1 2]
 [3 4]]

[array([[1, 2]]), array([[3, 4]])]

[[1 2]]
[[3 4]]


In [ ]:
# 2-D
arr = np.array([[1, 2], [3, 4]])
print(arr)
splt = np.array_split(arr, 2, axis = 0) # in two equal parts
print()
print(splt)
print()
print(splt[0])
print(splt[1])