# Array and Lists

In [6]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(type(x))
x
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [2]:
y = [1, 2, 3, 4]
print(y)
print(type(y))
y

[1, 2, 3, 4]
<class 'list'>


[1, 2, 3, 4]

# Array generate with input

In [7]:
l = []
for i in range(1, 5):
    inp_1 = int(input("enter:"))
    l.append(inp_1)
    
ar = np.array(l)
print(ar)
print(ar.ndim)

enter:56
enter:45
enter:45
enter:56
[56 45 45 56]
1


# 2-D 3-D Array

In [8]:
ar2 = np.array([[1,2,34,5], [35,4,2,1]])
print(ar2)
print(ar2.ndim)

[[ 1  2 34  5]
 [35  4  2  1]]
2


In [9]:
ar3 = np.array([[[2, 4, 8, 7], [2, 5, 1, 5], [1, 2, 4, 9]]])
print(ar3)
print(ar3.ndim)

[[[2 4 8 7]
  [2 5 1 5]
  [1 2 4 9]]]
3


In [10]:
arn = np.array([1, 2, 8, 7], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 8 7]]]]]]]]]]
10


# Zeros array

In [12]:
ar_zero14 = np.zeros(4) # 1-d array
ar_zero34 = np.zeros((3, 4))

print(ar_zero14)
print()
print(ar_zero34)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [14]:
ar_ones14 = np.ones(4) # 1-d array
ar_ones34 = np.ones((3, 4))

print(ar_ones14)
print()
print(ar_ones34)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty Array

In [16]:
ar_em = np.empty(5) #last memory will come
print(ar_em)

[ 1.    2.75  6.   10.75 17.  ]


# Range

In [18]:
ar_rn = np.arange(5)
print(ar_rn)

[0 1 2 3 4]


# Identity matrix array

In [20]:
ar_diag =np.eye(3)
print(ar_diag)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
ar_diag = np.eye(3, 5)
print(ar_diag)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Spacial matrix array Linespace

In [25]:
ar_lin = np.linspace(0, 10, num=5)
print(ar_lin)

[ 0.   2.5  5.   7.5 10. ]


# Random numbers

# Rand() (between 0 to 1)

In [26]:
var = np.random.rand(4) # 4 values 1-d
print(var)

[0.81668884 0.05311617 0.22718445 0.89728265]


In [27]:
var = np.random.rand(2,5)
print(var)

[[0.9236258  0.77678526 0.96371911 0.2796674  0.71727462]
 [0.42995512 0.84659215 0.04390565 0.19447327 0.22942361]]


# randn() (close to zero either +ve or -ve)

In [28]:
var = np.random.randn(5)
print(var)

[-2.70849865  0.48270248  0.40397038 -0.1725525   0.14287689]


# ranf() (between 0 to 1, 0 included, 1 excluded)

In [30]:
var = np.random.ranf(5)
print(var)

[0.68132926 0.40580477 0.21110319 0.89539529 0.407328  ]


# randint(min, max, total_values)

In [31]:
var = np.random.randint(5, 20, 7)
print(var)

[18 13 11 10 14 11 11]
