# Arithmetic operations on numpy array

In [ ]:
# a+b    np.add(a,b)
# a-b    np.subtract(a,b)
# a*b    np.multiply(a,b)
# a/b    np.divide(a,b)
# a%b    np.mod(a,b)
# a**b   np.power(a,b)
# 1/a    np.reciprocal(a)

# 1-D array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
res = a + 3
print(res)

[4 5 6 7]


In [3]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

res = a + b
print(res)

[2 4 6 8]


In [4]:
a = np.array([1,2,3,4])
res = a - 3
print(res)

[-2 -1  0  1]


In [5]:
a = np.array([1,2,3,4])
res = a * 3
print(res)

[ 3  6  9 12]


In [6]:
a = np.array([1,2,3,4])
res = a / 3
print(res)

[0.33333333 0.66666667 1.         1.33333333]


In [7]:
a = np.array([1,2,3,4])
res = a % 3
print(res)

[1 2 0 1]


In [8]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

res = np.add(a, b)
print(res)

[2 4 6 8]


In [9]:
a = np.array([1,2,3,4])

res = np.add(a, 3)
print(res)

[4 5 6 7]


In [13]:
a = np.array([1,2,3,4])

res = np.reciprocal(a)
print(res)

[1 0 0 0]


# 2-D array

In [11]:
a = np.array([[1,8,12,17], [14,20,30,40]])
b = np.array([[14,22,30,42], [1,45,35,24]])

res = a + b
print(res)

[[15 30 42 59]
 [15 65 65 64]]


In [12]:
a = np.array([[1,8,12,17], [14,20,30,40]])
b = np.array([[14,22,30,42], [1,45,35,24]])

res = a * b
print(res)

[[  14  176  360  714]
 [  14  900 1050  960]]


# Other Arithmetic operation

In [14]:
# np.min(x)
# np.max(x)
# np.argmin(x)
# np.argmax(x)
# np.sqrt(x)
# np.sin(x)
# np.cos(x)
# np.cumsum(x)

In [16]:
a = np.array([3, 2, 8, 5, 4, 7])
print("Max: ", np.max(a), ", Max at position: ", np.argmax(a))
print("Min: ", np.min(a), ", Min at position: ", np.argmin(a))

Max:  8 , Max at position:  2
Min:  2 , Min at position:  1


In [20]:
a = np.array([[2, 5, 3], [9, 2, 6]])
print(np.min(a, axis=0)) # min along column, and axis (0 -> along column and 1 -> along row for 2-d)
print(np.min(a, axis=1)) # min along row
print(np.max(a, axis=0)) # max along column
print(np.max(a, axis=1)) # max along row

[2 2 3]
[2 2]
[9 5 6]
[5 9]


In [21]:
a = np.array([3, 2, 8, 5, 4, 7])
print("Sq root: ", np.sqrt(a))

Sq root:  [1.73205081 1.41421356 2.82842712 2.23606798 2.         2.64575131]


In [23]:
a = np.array([45, 30, 180, 0, 145, 70])
print("Sin: ", np.sin(a))

Sin:  [ 0.85090352 -0.98803162 -0.80115264  0.          0.46774516  0.77389068]


In [24]:
a = np.array([45, 30, 180, 0, 145, 70])
print("Cos: ", np.cos(a))

Cos:  [ 0.52532199  0.15425145 -0.59846007  1.          0.88386337  0.6333192 ]


In [25]:
a = np.array([45, 30, 180, 0, 145, 70])
print("Cummulative Sum: ", np.cumsum(a)) # first, then first two add, then first three add and so on

Cummulative Sum:  [ 45  75 255 255 400 470]
