# Shape

In [1]:
import numpy as np

var = np.array([[1,2], [3, 4]]) # 2x2 matrix
print(var.shape)

(2, 2)


In [2]:
var = np.array([[1,2, 3, 4], [3, 4, 5, 0]]) # 2x4 matrix
print(var.shape)

(2, 4)


In [3]:
var = np.array([1,2, 3, 4], ndmin = 4) # 2x2 matrix
print(var)
print(var.ndim)
print(var.shape)

[[[[1 2 3 4]]]]
4
(1, 1, 1, 4)


# Reshape

In [13]:
var = np.array([1, 2, 3, 4, 5, 6]) # 1-D 1x6  1 2 3 4 5 6 in metrix
print(var.ndim)
print(var)
res = var.reshape(3, 2) # 3x2(2-D) or 2x3(2-D) or 6x1(1-D) possible
print()
print(res.ndim)
print(res)

1
[1 2 3 4 5 6]

2
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
var = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) # 1-D 1x9  1 2 3 4 5 6 7 8 9 in metrix
print(var.ndim)
print(var)
res = var.reshape(3, 3, 1) # 3x3x1(3-D) or 9x1(1-D) possible
print()
print(res.ndim)
print(res)
revertOneD = res.reshape(-1) # revert to 1-D
print()
print(revertOneD.ndim)
print(revertOneD)

1
[1 2 3 4 5 6 7 8 9]

3
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]

1
[1 2 3 4 5 6 7 8 9]
